version: "3"
services:

  mongo-toolbox:
    image: mongo:6.0
    container_name: mongo-toolbox
    volumes:
        - ./:/shared:z
    ports:
      - "6000:27017"
    expose:
      - "27017"
    restart: "no"
